---
name: cds411
channels:
  - defaults
  - jkglasbrenner
  - conda-forge
dependencies:
  - cython
  - jupyter
  - jupyterlab
  - matplotlib
  - nodejs
  - numpy-base
  - numpy
  - pandas
  - pandoc=2.2.3.2-0
  - pyhamcrest
  - python=3.6.5
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - yapf
  - pip:
    - black
    - nb_pdf_template
...
